### ISSUE TITLE
cant start/ install lock me now with OS X Sierra

### ISSUE THREAD

**Issue by nauni1977** [IGRSoft/LockMeNow#12]
Hello, 

I use a long time "lock me now" and I'm really happy for this functionality.

Since I upgraded to Sierra and installed "lock me now" one MAC has no problems to start "Lock Me Now" but the other one always shows the attached error. This means in english: "Can't open 'Lock Me Now'. The suggestion is to move this object into the trash." Now I have the options "abort" and "move to trash". (see screen shot)

Can you help me to solve this problem? I tried really a lot. I already removed the flag from filesystem that shows that the file is downloaded, but the message is still shown. The security option is set to "App Store and verified developers".

Thanks for your help and best regards

Oli 

![](imap://oliver%2Ewagner%40qutico%2Ede@vm01.intra.qutico.de:993/fetch%3EUID%3E.INBOX%3E22226?part=1.1.2&filename=image.png)
![image](https://cloud.githubusercontent.com/assets/5362697/19381466/fad21f3e-91fb-11e6-9a87-fd5ba9350b3d.png)

**Comment by luis-manzano** [comment]
Hi @nauni1977,

This issue is mentioned in other thread. Till it is solved, you can try executing the following command from a console, to allow temporarily any app to be executed:
`sudo spctl --master-disable`
Then you can try executing again the app pressing "CTRL" while opening contextual menu and selecting open.
Once app has been executed, you can set back in preferences the security option to "App Store and verified developers"or any other option you prefer.

Hope it helps.

**Comment by nauni1977** [comment]
Hello genoso,

thanks for your hint. I executed this command and restarted the computer. The problem is still the same. Even if I use finder with "CTRL" to open will cause this dialog. :-(

Do you have another idea?

Thanks in Advance

**Comment by luis-manzano** [comment]
Hi @nauni1977,

Are you using version 1.3.4? this is the one fixing MacOS Sierra. You can find download link in the thread for the **issue** called "_v1.3.3 not working_"

BR

**Comment by nauni1977** [comment]
Hello Genoso,
thanks for your information. I tried this with the link above and it worked. The new version of "Lock Me Now" solved the problem. Now it is also official released.

Thanks again for your feedback!

Best regards
